### PR TITLE
Updated gork and visualizations

### PR DESCRIPTION
**Pull request by MikeTheGreek**
Updated the gork filter for the new mono log format and changed the visualizations to use "cache_tag" rather than "upstream"

### CODE REVIEW

**Comment by VibroAxe** [comment]
Question: what logformat change are we talking about? I don't believe mono has had a log format change since we started it?

**Comment by MikeTheGreek** [comment]
I do not know when the format changed. i only started using mono a couple of weeks ago. The current gork filter is in the wrong order. as far as i am aware from Discord char @mintopia is also using this new filter.
Example of the current log.
`[blizzard] 192.168.0.82 / - - - [05/Jun/2019:17:14:16 +0000] "GET /tpr/viper/data/70/85/7085cb9426b854bed46952df6f35967c HTTP/1.1" 206 266240 "-" "-" "HIT" "level3.blizzard.com" "bytes=55111680-55377919"`

**Comment by VibroAxe** [comment]
@proto to confirm?

**Comment by MathewBurnett** [comment]
The commit changes the squid log grok which shouldn't be used if you don't have a WCCP/squid setup. The log line that you have added should  work with the existing grok. I will have a look at the upstream stuff as that approach pre-dates cache-tags and could probably be cleaner

looks like line 65 is the match for your setup, which should work

**Comment by VibroAxe** [comment]
@mikethegreek can you resolve the conflict?

**Comment by MikeTheGreek** [comment]
fixed the conflict but i will have to look at the gork filters more when i have some spare time as it was not matching anything at all. did not notice there was two gork filters

**Comment by MikeTheGreek** [comment]
well i have resolved the issue as to why it was showing as "unknown" in the visualizations.
It seems that when i first load data in to fresh ELK install it shows as "unknown" refresh it and it will show up correctly.
I will close this pr and add create a new one adding epic games and wsus

**Pull request closed without merging**
