### PR TITLE
Add configurations for 6.x and 7.x ELK stacks

### LINKED ISSUE #9: ELK 7.x support
I tried upgrading my ELK stack to 7.x over the weekend without success.

I'm wondering if anybody has managed to get the configuration working with ELK 7.x?
It looked to me like that `my_index` field for the indexes was not being created properly.

If anybody has had success deploying this on 7.x could you please share the appropriate logstash and filebeat config and an object export from Kibana?

### PR DESCRIPTION
**Pull request by nightah**
Changes to logstash and filebeat from 6.x to 7.x has deprecated some fields that the original configuration was reliant on.

The supplied logstash config has been separated into a 6.x and 7.x variant.

Closes #9.

### CODE REVIEW

**Comment by nightah** [comment]
I also think it's worthwhile changing the `myindex` field from `logstash-` to `lancache-`.
This just means the indicies are easier to identify as relating to lancache as opposed to something much more ambiguous.

Happy to add that on to this PR if preferred,

**Comment by VibroAxe** [comment]
Seems like a good idea to me, I have a small concern over breaking changes. @MathewBurnett care to weigh in?

**Comment by nightah** [comment]
Technically it’s not a breaking change because the index from the json import is `*`.

I’m going to update this to be more specific in the PR.

Only issue is that the export includes objects for squid etc, which I do not use and as far I can tell isn’t documented anywhere.

Perhaps the config and export should be seperate for the monolithic setup and squid?
Happy to do that too if we prefer, someone else will eventually need to add the json export for squid though.

**Comment by MathewBurnett** [comment]
@nightah you don't happen to know how `if [source] =~ "access" or [log][file][path] =~ "access"` behaves do you?

**Comment by nightah** [comment]
`[source]` is deprecated in v7, this has been replaced with `[log][file][path]`. To answer your question though, the former does not work and the latter does work.

I've been using the v7 stack for a couple months now: https://nerv.cx/fx1Cd

**Comment by VibroAxe** [comment]
@nightah the question is more if by using an `or` statement in the logstash config we can have a unified file for both V6 and v7, or if the reference to the deprecated field breaks the config altogether

**Comment by nightah** [comment]
Looks like the deprecated fields do work on the newer version (for now) we might need to review this in the future though.

I've just pushed a commit which unifies the config all in to a single file for now.

**Comment by VibroAxe** [comment]
Anyone got a logstash 6 we can test this on?

**Comment by Mattz0r** [comment]
Not sure about v6, but this worked like a dream for v7 for me just now.

**Comment by MathewBurnett** [comment]
I haven't completely forgotten about this but its been a while since we have had an event that didn't get cancelled by some momentary disaster so i haven't had a chance to play with it

**Comment by ScholliYT** [comment]
This config works for me on ELK version 7.9.1

**Pull request merged**
